### PR TITLE
mobile formatting improvements

### PR DESCRIPTION
**Pull request by nobane**
References #120 #148 

This PR does a lot to improve mobile formatting. My focus was on the forms and viewing lists of alerts. Instead of having a table that goes too wide on mobile, the alerts are displayed in a list that fits to screen.

This PR also adds support for SASS-like styling via precss (yay!).

More mobile improvement could be done, this is just an update that addresses the most likely mobile used pages/functionality of the site.

### CODE REVIEW

**Comment by justinnoah** [comment]
@spectralsun all is looking pretty good. Though, I think we need to tweak the mobile burger menu. Maybe it is just me, but some of the menu items are not very easy to read (not contrasty enough).

screen shot 2016-10-25 at 16 32 35

**Comment by nobane** [comment]
@justinnoah I agree, I meant to address the mobile dropdown menu. Should probably be worth noting that there are no hover states on mobile.

I'll get that looking pretty :)

**Comment by justinnoah** [comment]
Also, the Logo shown at login should probably be scaled as well.

screen shot 2016-10-25 at 16 50 20

**Comment by justinnoah** [comment]
Once those are corrected, besides not being able to view response as admin to verify prettification ( #157 ) we should be able to merge this. It looks great.

**Comment by nobane** [comment]
@justinnoah updated this PR to remove our one big, nasty external CSS file. All of our CSS is localized per React component.

Also did a fair bit of refactoring with the Navbar and Chrome to accommodate a better mobile nav experience.

**Comment by justinnoah** [comment]
@spectralsun please fix merge conflicts. unless you wanted to make changes, besides the conflicts, this is ready to merge.

**Comment by nobane** [comment]
Closes #148 #120

**Pull request merged**
